from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors


def generate_pdf(
    file_path,
    similarity,
    risk,
    threat,
    alerts,
    explanation,
    recommendations,
    analysis_time,
    integrity_status,
    original_hash,
    uploaded_hash
):
    styles = getSampleStyleSheet()

    pdf = SimpleDocTemplate(file_path)
    story = []

    story.append(Paragraph("<b>Secure Digital IP Monitoring System</b>", styles["Title"]))
    story.append(Paragraph("AI-Powered Intellectual Property Risk Investigation Report", styles["Heading2"]))
    story.append(Spacer(1, 12))

    summary_data = [
        ["Analysis Time", analysis_time],
        ["Content Similarity", f"{similarity}%"],
        ["Overall Risk Score", f"{risk}/100"],
        ["Threat Level", threat],
        ["Integrity Status", integrity_status],
    ]

    summary_table = Table(summary_data, colWidths=[180, 300])
    summary_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#dbeafe")),
        ("TEXTCOLOR", (0, 0), (-1, -1), colors.black),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("PADDING", (0, 0), (-1, -1), 8),
    ]))

    story.append(summary_table)
    story.append(Spacer(1, 16))

    story.append(Paragraph("<b>Document Integrity Verification</b>", styles["Heading2"]))
    story.append(Paragraph(f"<b>Original SHA-256:</b> {original_hash}", styles["BodyText"]))
    story.append(Paragraph(f"<b>Uploaded SHA-256:</b> {uploaded_hash}", styles["BodyText"]))
    story.append(Spacer(1, 16))

    story.append(Paragraph("<b>Detected Alerts</b>", styles["Heading2"]))
    if alerts:
        for alert in alerts:
            story.append(Paragraph(f"• {alert}", styles["BodyText"]))
    else:
        story.append(Paragraph("No suspicious alerts detected.", styles["BodyText"]))

    story.append(Spacer(1, 16))

    story.append(Paragraph("<b>AI Security Explanation</b>", styles["Heading2"]))
    story.append(Paragraph(explanation, styles["BodyText"]))
    story.append(Spacer(1, 16))

    story.append(Paragraph("<b>Recommended Actions</b>", styles["Heading2"]))
    for item in recommendations:
        story.append(Paragraph(f"• {item}", styles["BodyText"]))

    story.append(Spacer(1, 20))
    story.append(Paragraph("Generated by Secure Digital IP Monitoring System v1.0", styles["Italic"]))

    pdf.build(story)